### ISSUE TITLE
can SDWebImage convert image to SVG?

### ISSUE THREAD

**Issue by bizibizi** [SDWebImage/SDWebImageSVGCoder#1]

**Comment by dreampiggy** [comment]
Seems currently, it can not. Because it obeys the API design for us. We supports to encoding a `UIImage` representation into Data, however, since SVG is just a vector data format without compression, if you knows the UIImage is SVG representation, you can directly grab the data, no encoding needed. (You can use the API to grab `CGPDFPageRef`)

Compared to  Bitmap format (like JPEG/PNG), the compression data is not equal to bitmap vector data, so it need to re-encoding. It takes CPU && RAM, this is why it's more complicated.

For CALayer layer tree, you can try, using SVGKit's API for CALayer, to parse the layer into SVG DOM. But it's a little buggy, you can try it yourself.

**Comment by bizibizi** [comment]
Okay, but how can I save UIIMage as SVG?

**Comment by dreampiggy** [comment]
@bizibizi Typo, that `CGPDFPageRef` is PDF. I mixed them :)

For All SVG format generated by SDWebImageSVGCoder, it's a `SDSVGImage` instance, which is subclass of `UIImage`.

It has a property [SVGImage](https://github.com/SDWebImage/SDWebImageSVGCoder/blob/master/SDWebImageSVGCoder/Classes/SDSVGImage.h#L15) to grab the SVGKit's image representation.

See the third-party [SVGKit](https://github.com/SVGKit/SVGKit/blob/3.x/Source/SVGKImage.h#L66) API, it have a `source` property, which is `SVGKSource` instance. And because SDWebImage only pass the raw data to generate SVGKImage, it should be [SVGKSourceNSData](https://github.com/SVGKit/SVGKit/blob/3.x/Source/Sources/SVGKSourceNSData.h) class, which you can directly get the `NSData`.

For all the code above, can be concluded into this demo code.

```objective-c
    // Only support SVGKImage wrapper
    if (![image isKindOfClass:SDSVGImage.class]) {
        return nil;
    }
    SVGKImage *svgImage = ((SDSVGImage *)image).SVGImage;
    if (!svgImage) {
        return nil;
    }
    SVGKSource *source = svgImage.source;
    // Should be NSData type source
    if (![source isKindOfClass:SVGKSourceNSData.class]) {
        return nil;
    }
    return ((SVGKSourceNSData *)source).rawData;
```

If you want, I can put this code into the SVG coder implementation, where you can use `-[UIImage sd_ImageAsFormat:SDImageFormatSVG]` to grab the data ?

**Comment by dreampiggy** [comment]
Wait me for a hour for this feature request.

**Comment by dreampiggy** [comment]
Supported by v0.3.0. You can grab the SVG image generated from SDWebImage, to original SVG data. See: [changelog](https://github.com/SDWebImage/SDWebImageSVGCoder/releases/tag/0.3.0)

**Comment by bizibizi** [comment]
@dreampiggy thanks, i will test that and message if something wrong
