### ISSUE TITLE
CoreSVG is a private framework

### ISSUE THREAD

**Issue by lapfelix** [SDWebImage/SDWebImageSVGCoder#13]
[The switch from SVGKit to CoreSVG](https://github.com/SDWebImage/SDWebImageSVGCoder/pull/10) seems to be a little dangerous.

Specifically, [all of these functions and method declarations](https://github.com/SDWebImage/SDWebImageSVGCoder/blob/master/SDWebImageSVGCoder/Classes/SDImageSVGCoder.m#L15-L33) are private and since the framework is private, Apple could change their method/function signature in an upcoming iOS/macOS update without any warning. It could also lead to apps being refused from the App Store since using private APIs isn't allowed.

**Comment by dreampiggy** [comment]
Until we have another choice. Actually.

In next release, I'll encrypt all the private API call without the stringify symbol, which can avoid potential issue. I'll do this in hours.

For exist SVGKit integration, you can always using [SDWebImageSVGKitPlugin](https://github.com/SDWebImage/SDWebImageSVGKitPlugin). It's here and does not disappear.

The reason is simple:

SVGKit is not a **Stable Framework and Maintainer is not able to drive that forward development**. So, we as a downstream dependency, can not rely on that framework. That's the question.
