### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by piroznoe** [SDWebImage/SDWebImageSVGCoder#3]
in line:

for( NSString* parserNamespace in extension.supportedNamespaces )

Thread 12: EXC_BAD_ACCESS (code=1, address=0x7b56d99f0)

**Comment by dreampiggy** [comment]
Seems a bug of SVGKit itself. Is this issue related ?

https://github.com/SVGKit/SVGKit/pull/605

Actually, for your App target, you'd better using the git source dependency for SVGKit. Because that project seems not obey the Git Flow pipeline and semversion. So do the following:

```
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
```

Maybe I can update the Readme about this.

**Comment by dreampiggy** [comment]
This issue no longer appeared on the latest 3.x branch of SVGKit.
