### ISSUE TITLE
Crash on svg image

### ISSUE THREAD

**Issue by AndriiPetrovDev** [SDWebImage/SDWebImageSVGCoder#43]
Try to open this image https://openseauserdata.com/files/b809fe0925eb3629bb1d3edb1fafcc88.svg
SDWebImage crashes because "NSFont can't be nil"

**Comment by dreampiggy** [comment]
Seems SVG use a font which native iOS platform does not embed.

Does this a Objective-C exception (or C++ exception) which can be handled by our user level code ?

If so, we can add a protect here. To make it `Load SVG failed` but not crash your user app.

**Comment by dreampiggy** [comment]
```
font-family="宋体"
```

**Comment by AndriiPetrovDev** [comment]
It will be really nice.

**Comment by AndriiPetrovDev** [comment]
Can we solve such problems for all possible alphabets?

**Comment by dreampiggy** [comment]
> Does this a Objective-C exception (or C++ exception) which can be handled by our user level code ? 

Did you test this ?

**Comment by osmantufekci** [comment]
There is another crash, EXC_BADACCESS on SDCGSVGDocumentWriteToData method. But it happens only at first load, subsequent load attempt won't crash. I also tried with [SDWebImageSVGNativeCoder](https://github.com/SDWebImage/SDWebImageSVGNativeCoder) but this time it shows the file as pure black.

This is the svg file; 
![general](https://user-images.githubusercontent.com/6459235/235932615-c9d64268-d331-4e1f-9a82-cde3511e80bc.svg)

as text:
[general.txt](https://github.com/SDWebImage/SDWebImageSVGCoder/files/11383074/general.txt)

**Comment by dreampiggy** [comment]
`SDCGSVGDocumentWriteToData` is used to re-export UIImage to NSData. So why do you mean`But it happens only at first load, subsequent load attempt won't crash` ?

I don't think these two is the same issue. SDWebImage itself should not re-encode SVG image to NSData if you don't specify this (using thumbnail or transformer)

Actually, the `SVG export` feature is not really useful in general, because SVG is vector image format. For the re-export, you can just save the data (download from SVG URL) and re-read it

**Comment by dreampiggy** [comment]
Is this logic bug ? Any demo can reproduce your `But it happens only at first load, subsequent load attempt won't crash` ?

For normal WebImage loading process, it should not trigger re-encode logic.

1. Query Cache failed
2. Download SVG Data
3. Create UIImage (using CoreSVG)
4. Store Data to Disk, UIImage to Memory
5. Finish Callback
