### ISSUE TITLE
svg <text> tag not show with this

### ISSUE THREAD

**Issue by iPermanent** [SDWebImage/SDWebImageSVGCoder#54]
when a svg has <text> tag, the text content not show, as this
Here show with chrome:
<img width="889" alt="image" src="https://github.com/user-attachments/assets/a5a38172-0eea-485a-8cc4-3c5e23e6cfa4">
but here show with the phone with SDWebimageSVGCode:
![IMG_7067](https://github.com/user-attachments/assets/c00bf420-404a-4954-9f67-107f9f5c1119)
by the way  the SDWebimageNativeCoder has same problem

**Comment by iPermanent** [comment]
![09F_01_dapeixunjiaoshi](https://github.com/user-attachments/assets/aae7b538-fcc5-4688-b42b-dd61805e4bb8)
Here is the svg file

**Comment by dreampiggy** [comment]
Render issue can not be fixed by me. It's Apple's internal SDK's behavior.

I guess this may related to some font issue. Changing your SVG's font may workaround this.

---

You also can have a try with: https://github.com/SDWebImage/SDWebImageSVGNativeCoder

If you care about SVG render "correctness", always don't use any Apple's SDK. Use the third-party one like that Adobe `svg-native` based coder.

**Comment by dreampiggy** [comment]
`font-family="PingFangSC-Medium, PingFang SC"`

Remove this from all svg attribute, or use built-in font to have a try ?

Apple's CoreSVG use https://developer.apple.com/design/human-interface-guidelines/sf-symbols, I don't know whether they support `Font/Text` attribute

**Comment by iPermanent** [comment]
> `font-family="PingFangSC-Medium, PingFang SC"`
> 
> Remove this from all svg attribute, or use built-in font to have a try ?
> 
> Apple's CoreSVG use https://developer.apple.com/design/human-interface-guidelines/sf-symbols, I don't know whether they support `Font/Text` attribute

Thanks for your advice, I just read about the adobe svg documention, and find that text tag will not display on any mobile phone, and we change the text tag with path draw instead and it's show well.
